### ISSUE TITLE
🏄 Apply RSR v0.81.0

### ISSUE THREAD

**Issue by in4s** [j4s/validation#83]
- [x] 🌕 !!!!! edit namespace j4s/validation in RSR_apply.txt document
- [x] 🌕 Add milestone 🏄 Apply RSR v0.81.0
- [x] 🌕 Set closest version milestone to this issue
- [x] 🌕 Pin this issue; Pin it to the left
- [ ] ** 🌗 Add repo shortcut to webShortcuts
- [x] 🌕 (from_0.15.6) [Milestone](https://github.com/j4s/validation/milestones/new) and [Labels](https://github.com/j4s/validation/labels):
    - [ ] Add milestone 📚 Someday, Maybe
    - [ ] Edit label enhancement set color code #16c60c
    - [x] Add labels: rsr-tinker (new App\RSR('j4s/validation'))->addLabels();
        - [ ] Add label gitflowM with color code #ffb900
        - [ ] Add label canProceed with color code #5319e7
        - [ ] Add label Urgent with color code #b60205
        - [ ] Add label test with color code #0366d6
        - [ ] Add label refactoring with color code #cccccc
        - [ ] Add label bigIssue with color code #c4580b [from_0.14.0]
        - [ ] Add label subIssue with color code #ffbf8f [from_0.14.0]
        - [x] Add label lowPriority with color code #fef2c0 [from_0.15.0]
        - [x] Add label backwardIncompatible with color code #c90c7a [from_0.15.0]
        - [x] Add label BlackLongCheckpoint with color code #000000 [from_0.15.2]
        - [x] Add label turboRelease with color code #991acc [from_0.15.6]
- [ ] 🌗 add label gitflowM to this issue
- [x] 🌕 Create issues if their RSR version higher than current RSR version of the project
    - [x] 🌕 2. Git settings                 [from_0.16.0](https://github.com/j4s/validation/issues/new/?milestone=🏄+Apply+RSR+v0.81.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+2.+Git+settings&body=-+%5B+%5D+%F0%9F%8C%97+%5BCMD%5D+%60git+clone+https://github.com/j4s/validation.git%60+%28git%40github.com:j4s/validation.git%29%0D%0A-+%5B+%5D+%F0%9F%8C%95+Set+up+or+check+global+and+non-global+settings+for+particular+user.+%28for+in4s:+https://github.com/in4s/NewRepo/blob/main/gitSettings.txt%29%0D%0A-+%5B+%5D+**+%F0%9F%8C%95+For+each+host%28local+repository%29+of+this+project+make+issue+Check+Git+Settings%0D%0A-+%5B+%5D+**+%F0%9F%8C%95+For+each+host+Generate%2C+install+and+activate+deploy+keys%0D%0A-+%5B+%5D+**+%F0%9F%8C%97+%5BPHPStorm%5D+Create+New+project+from+existing+files%0D%0A-+%5B+%5D+%F0%9F%8C%97+git+pull%0D%0A-+%5B+%5D+%F0%9F%8C%97+git+checkout+-b+%60rsrUpdateTo_v0.81.0%60%0D%0A-+%5B+%5D+%F0%9F%8C%97+%5BCMD%5D+add+files+from+the+desired+template+folder%0D%0A-+%5B+%5D+%F0%9F%8C%97+Edit+README.md+file+%28set+repo+name%29%0D%0A-+%5B+%5D+%F0%9F%8C%97+git+add+.+%2C+git+commit+-m+%60close+%23CURRENT_ISSUE_NUMBER%60%0D%0A-+%5B+%5D+🌓+Close+this+issue)
    - [x] 🌕 3. GitHub's settings            [from_0.81.0](https://github.com/j4s/validation/issues/new/?milestone=🏄+Apply+RSR+v0.81.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+3.+GitHub+and+IDE+settings&body=-+%5B+%5D+%F0%9F%8C%95+%5BGITHUB%5D+%5BREPOSITORY+-%3E+Settings%5D%28https://github.com/j4s/validation/settings%29+Turn+on+%60Automatically+delete+head+branches%60%0D%0A-+%5B+%5D+%F0%9F%8C%95+%5BGITHUB%5D+%5BREPOSITORY+-%3E+Settings+-%3E+Branches%5D%28https://github.com/j4s/validation/settings/branches%29+Add+Branch+protection+rules+%28For+each+one+enable+4+checkpoints:+first+one%2C+%2B+2+its+subs+%2B+Require+conversation+resolution+before+merging%29:%0D%0A++++-+%5B+%5D+%60main%60%0D%0A-+%5B+%5D+%F0%9F%8C%93+Remove+unnecessarily+version+branches+%21%21%21+not+branch+protection+rules%2C+but+branches+%21%21%21%0D%0A-+%5B+%5D+%F0%9F%8C%93+Uncheck+%22Deployment+-%3E+Options+-%3E+Skip+external+changes%22%2C%0D%0A-+%5B+%5D+%F0%9F%8C%93+Set+%22No%22+to+%22Deployment+-%3E+Options+-%3E+Warn+when+uploading+over+newer+file:%22%0D%0A-+%5B+%5D+%F0%9F%8C%95+Set+up+PhpStorm:+Copy+%60IsNav%60%3B+Shift%2C+Shift%3B+Ctrl+%2B+V%3B+ESC%3B+Copy+%60%23%28%5Cd*%29%60%3B+Alt+%2B+Insert%3B+Ctrl+%2B+V%3B+Copy+%60https://github.com/j4s/validation/issues/%241%60%3B+TAB%3B+Ctrl+%2B+V%3B+edit+repo+name%3B+test+on+%23120%3B+apply%3B+test%0D%0A-+%5B+%5D+Close+this+issue)
    - [x] 🌓 4. Update GitHub template files [from_0.16.0](https://github.com/j4s/validation/issues/new/?milestone=🏄+Apply+RSR+v0.81.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+4.+Update+GitHub+template+files&body=-+%5B+%5D+**+%F0%9F%8C%93+Sync+files+with+the+desired+template+folder%0D%0A-+%5B+%5D+%F0%9F%8C%93+git+add+.+%2C+git+commit+%60%23CURRENT_ISSUE_NUMBER+GitHub+template+files+updated%60%0D%0A-+%5B+%5D+Close+this+issue)
    - [x] 🌕 8. Edit RSR version number      [from_v0.81.0](https://github.com/j4s/validation/issues/new/?milestone=🏄+Apply+RSR+v0.81.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+8.+Edit+RSR+version+number&body=-+%5B+%5D+%F0%9F%8C%95+Edit+Repository+description+add/edit+%28RSR+v0.81.0%29+at+the+end%0D%0A-+%5B+%5D+%F0%9F%8C%95+Edit+README.md:+Complies+with+standard+RSR+v0.81.0%0D%0A-+%5B+%5D+%F0%9F%8C%95+git+add+.+%2C+git+commit+%60close+%23CURRENT_ISSUE_NUMBER%60%0D%0A-+%5B+%5D+%F0%9F%8C%95+Create+pull+request+to+the+%60main%60+branch%2C+Review+it%2C+Merge+it%0D%0A-+%5B+%5D+%F0%9F%8C%95+Create+pull+requests+to+other+active+versions+branches%2C+Review+them%2C+Merge+them+%28if+exists%29%0D%0A-+%5B+%5D+%F0%9F%8C%95+Check:+This+issue+is+closed%0D%0A-+%5B+%5D+%F0%9F%8C%95+Remove+local+branch)
    - [ ] 🌗 9. Release version              [from_0.1.0](https://github.com/j4s/validation/issues/new/?milestone=🏄+Apply+RSR+v0.81.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+9.+Release+version+v0.0.0&body=) (optional)
    - [ ] ** 🌗 10. Add Collaborators ...    [from_0.10.1](https://github.com/j4s/validation/issues/new/?milestone=🏄+Apply+RSR+v0.81.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+10.+Add+Collaborators+to+repository&body=-+%5B+%5D+**+Add+collaborators%0D%0A-+%5B+%5D+**+Add+issues+for+each+collaborator+by+the+link:+https://github.com/in4s/gitflow/issues/new%3Ftitle%3DAccept%2Binvitation%2Bto%2Bj4s/validation%2Brepository%2B*%26labels%3DgitflowM%2CcanProceed%2CUrgent%26body%3DConfirm%2Bit%2Bby%2Bthis%2Blink:%2Bhttps://github.com/j4s/validation/invitations) (optional)
    - [ ] ** 🌗 11. Check Confirm Collabor...[from_0.10.1](https://github.com/j4s/validation/issues/new/?milestone=🏄+Apply+RSR+v0.81.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+11.+Check+Confirm+Collaborators+to+repository&body=) (optional)
- [x] 🌓 git status
- [x] 🌓 git checkout main
- [x] 🌓 git pull
- [x] 🌓 git checkout -b `rsrUpdateTo_v0.81.0`
- [x] 🌕 Apply each step of this process to the repository
- [x] 🌕 Check closing issues for RSR process
- [x] 🌕 Close milestone `🏄 Apply RSR v0.81.0`
- [x] 🌕 Close this issue
- [x] 🌕 Unpin it
