### ISSUE TITLE
⚡ Release v1.0.0

### ISSUE THREAD

**Issue by in4s** [j4s/validation#89]
- [x] ** Update RSR (optional)
- [x] git checkout main
- [x] git pull
- [x] git checkout -b Release_v1.0.0_#89
- [x] Fix the current version number in files:
    - [x] In README.md
    - [x] In composer.json
- [x] git add . , git commit -m "⚡ Release v1.0.0 close #89"
- [ ] (C*rmr) By process IV Create pull request "⚡ Release v1.0.0 close #89"
------
- [ ] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [ ] click and save https://github.com/j4s/validation/releases/new?tag=v1.0.0&target=main
- [ ] Increase the version number in local data.js
- [ ] Remove local branch
- [ ] click and save https://github.com/j4s/validation/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v1.0.0+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [ ] Pin this test issue; Pin it to the left
- [ ] Close milestone with current version name
- [ ] Unpin this issue
